import { ThumbnailConcept, ConceptGenerationResult } from "./types";
import {
  getConceptTextStyle,
  getResolvedTextStyle,
  getTextMode,
  getTextModeLabel,
} from "./text-overlay";

export function buildMarkdownPacket(
  result: ConceptGenerationResult,
  starred?: Set<string>
): string {
  const { brief, concepts, abPlan } = result;
  const target = starred
    ? concepts.filter((c) => starred.has(c.id))
    : concepts;

  const lines: string[] = [];
  lines.push(`# ThumbSnare — Thumbnail Concept Pack`);
  lines.push("");
  lines.push(`**Video:** ${brief.videoTitle}`);
  lines.push(`**Angle:** ${brief.angle}`);
  lines.push(`**Category:** ${brief.topicCategory || "—"}`);
  lines.push(`**Audience:** ${brief.targetAudience || "—"}`);
  lines.push(`**Tone:** ${brief.tone}`);
  lines.push(`**Text Mode:** ${getTextModeLabel(getTextMode(brief))}`);
  if (getTextMode(brief) !== "none") {
    lines.push(
      `**Text Style:** ${(brief.textStyle || "recommended") === "recommended" ? "AI recommended per concept" : getResolvedTextStyle(brief)}`
    );
  }
  if (brief.channelContext) lines.push(`**Channel Context:** ${brief.channelContext}`);
  if (brief.constraints) lines.push(`**Constraints:** ${brief.constraints}`);
  lines.push("");
  lines.push(`---`);
  lines.push("");

  if (starred) {
    lines.push(`## Starred Concepts (${target.length})`);
  } else {
    lines.push(`## All Concepts (${target.length})`);
  }
  lines.push("");

  target.forEach((c, i) => {
    lines.push(`### ${i + 1}. ${c.conceptName}`);
    lines.push("");
    lines.push(`**Face Expression:** ${c.faceExpression}`);
    lines.push("");
    lines.push(
      `**Text Overlay:** “${c.textOverlay.text}” — ${c.textOverlay.placement} · ${getConceptTextStyle(c, brief)}`
    );
    lines.push("");
    lines.push(`**Color Psychology:**`);
    lines.push(`- Primary: ${c.colorPsychology.primaryColor}`);
    lines.push(`- Emotion: ${c.colorPsychology.emotion}`);
    lines.push(`- Contrast: ${c.colorPsychology.contrastNote}`);
    lines.push("");
    lines.push(`**A/B Variant Hint:** ${c.abVariantHint}`);
    lines.push("");
    lines.push(`**Platform Notes:** ${c.platformNotes}`);
    lines.push("");
    lines.push(`**Image Prompt:**`);
    lines.push("```text");
    lines.push(c.imagePrompt);
    lines.push("```");
    lines.push("");
    lines.push(`---`);
    lines.push("");
  });

  lines.push(`## A/B Test Plan`);
  lines.push("");
  lines.push(abPlan);
  lines.push("");
  lines.push(`---`);
  lines.push("");
  lines.push(`_Generated by ThumbSnare — youtube-thumbnail-studio_`);

  return lines.join("\n");
}
