import { describe, it, expect } from "vitest";
import { buildMarkdownPacket } from "../src/lib/export";
import { ConceptGenerationResult } from "../src/lib/types";

function makeResult(): ConceptGenerationResult {
  return {
    brief: {
      videoTitle: "How I Lost $50K in Crypto",
      angle: "Document the mistakes that wiped out my savings",
      topicCategory: "Finance / Crypto",
      targetAudience: "Retail investors",
      tone: "dramatic",
      textMode: "post-process",
      textStyle: "impact",
      channelContext: "Personal finance channel",
      constraints: "No gambling imagery",
    },
    concepts: [
      {
        id: "1",
        conceptName: "Wallet Drop",
        imagePrompt: "A dramatic close-up of empty hands dropping a wallet, dark moody lighting, red undertones",
        faceExpression: "Shock / wide eyes, jaw slightly open",
        textOverlay: { text: "GONE", placement: "center" },
        colorPsychology: { primaryColor: "red", contrastNote: "high contrast on dark bg", emotion: "loss, danger" },
        abVariantHint: "Text-light version without the word 'GONE'",
        platformNotes: "Test at 5–6s mark where CTR is lowest",
      },
      {
        id: "2",
        conceptName: "Chart Crash",
        imagePrompt: "A steep red candlestick chart plunging downward, blurred background",
        faceExpression: "Disbelief / raised eyebrows, mouth open",
        textOverlay: { text: "$50K VANISHED", placement: "top-left" },
        colorPsychology: { primaryColor: "darkred", contrastNote: "crimson on black", emotion: "panic, urgency" },
        abVariantHint: "Close-up face instead of chart focus",
        platformNotes: "Best for finance niche retargeting",
      },
    ],
    abPlan: "Test dramatic face vs chart-focused thumbnails. Measure CTR at 5s and 15s impressions.",
  };
}

describe("buildMarkdownPacket", () => {
  it("renders header with video title and metadata", () => {
    const md = buildMarkdownPacket(makeResult());
    expect(md).toContain("# ThumbSnare — Thumbnail Concept Pack");
    expect(md).toContain("How I Lost $50K in Crypto");
    expect(md).toContain("Finance / Crypto");
    expect(md).toContain("Retail investors");
    expect(md).toContain("dramatic");
    expect(md).toContain("**Text Mode:** Post-process");
    expect(md).toContain("**Text Style:** impact");
    expect(md).toContain("center · impact");
    expect(md).toContain("Personal finance channel");
    expect(md).toContain("No gambling imagery");
  });

  it("renders all concepts by default", () => {
    const md = buildMarkdownPacket(makeResult());
    expect(md).toContain("Wallet Drop");
    expect(md).toContain("Chart Crash");
    expect(md).toContain("GONE");
    expect(md).toContain("$50K VANISHED");
    expect(md).toContain("Shock / wide eyes");
    expect(md).toContain("high contrast on dark bg");
    expect(md).toContain("loss, danger");
  });

  it("renders A/B plan and footer", () => {
    const md = buildMarkdownPacket(makeResult());
    expect(md).toContain("## A/B Test Plan");
    expect(md).toContain("Test dramatic face vs chart-focused thumbnails");
    expect(md).toContain("Generated by ThumbSnare");
  });

  it("filters to starred concepts only when starred set provided", () => {
    const starred = new Set(["2"]);
    const md = buildMarkdownPacket(makeResult(), starred);
    expect(md).not.toContain("Wallet Drop");
    expect(md).toContain("Chart Crash");
    expect(md).toContain("Starred Concepts");
  });

  it("shows zero count when starred set filters everything", () => {
    const starred = new Set<string>([]);
    const md = buildMarkdownPacket(makeResult(), starred);
    expect(md).toContain("Starred Concepts (0)");
  });

  it("escapes markdown in text overlay safely", () => {
    const result = makeResult();
    result.concepts[0].textOverlay.text = "**bold** [link](url)";
    const md = buildMarkdownPacket(result);
    expect(md).toContain("**bold** [link](url)");
  });

  it("renders image prompt inside code block", () => {
    const md = buildMarkdownPacket(makeResult());
    expect(md).toContain("```text");
    expect(md).toContain("A dramatic close-up");
    expect(md).toContain("```");
  });

  it("shows 'All Concepts' heading when no starred set", () => {
    const md = buildMarkdownPacket(makeResult());
    expect(md).toContain("## All Concepts (2)");
  });

  it("omits optional fields when blank", () => {
    const result = makeResult();
    result.brief.channelContext = "";
    result.brief.constraints = "";
    const md = buildMarkdownPacket(result);
    expect(md).not.toContain("Channel Context:");
    expect(md).not.toContain("Constraints:");
  });
});
